trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Job1
    steps:
    - bash: echo First Job
  - job: job2
    steps:
    - bash: echo Second job
- stage: DevDeploy
  jobs:
  - job: DevDeployJob
    displayName: 'Run DEV deploy Job'
    steps:
    - bash: echo DevDeployJob
- stage: QADeploy
  jobs:
    - job: QADeployJob
      displayName: 'Run QA deploy Job'
      steps:
        - bash: echo QADeployJob
- stage: ProdDeploy
  jobs:
    - job: ProdDeployJob
      displayName: 'Run Prod deploy Job'
      steps:
        - bash: echo ProdDeployJob


